# Site settings
title: GregA100K
email: grega100k@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Greg Allen's dev blog taking a look at things that maybe aren't as easy to see as they could be.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://GregA100k.github.io" # the base hostname & protocol for your site
twitter_username: GregAllen100k
github_username:  GregA100K

# Build settings
markdown: kramdown
